jrbuilding/config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end

end

Rails.application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "tenants/generate_lease" => "tenants#generate_lease"
  get "tenants/expense_addendum" => "tenants#expense_addendum"
  post "cheques/single_report" => "cheques#single_report"
  get "cheques/all_report" => "cheques#all_report"
  get "buildings/getgst" => "buildings#getgst"
  get "buildings/getqst" => "buildings#getqst"
  get "tenants/get_tenant_id" => "tenants#get_tenant_id"
  get "tenants/get_tenant_table" => "tenants#get_tenant_table"
  get "expenses/expensesforyear" => "expenses#expensesforyear"
  get "expenses/expenses_for_building" => "expenses#expenses_for_building"
  get "buildings/properties_for_building" => "buildings#properties_for_building"
  get "tenants/tenants_in_local" => "tenants#tenants_in_local"
  get "helps/download_master_lease"
  get "helps/download_master_expense" => "helps#download_master_expense"
  post "tenants/send_mail" => "tenants#send_mail"

  root :to => 'buildings#index', :constraints => AuthConstraint.new, as: :authenticated_root
  root :to => 'sessions#new'

  resources :users
  resources :buildings
  resources :properties
  resources :tenants
  resources :sessions 
  resources :expenses
  resources :masterleasepdfforms
  resources :expensepdfforms  
  resources :helps
  resources :cheques  
  match '*path', :to => 'errors#routing', via: [:get, :post]

end

jrbuilding/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bimage">
	<div class="bimage">
		<head>
				  
		  <div class="pagetop">	
		  	
		  </div>

		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>
		</head>
		<body>
			
			<script type="text/javascript"> </script>
			<div id="user_nav">
			    	<% if current_user %>

						    <div class="container">
								<nav class="navbar navbar-default navbar-static-top" role="navigation">
						  			<div class="container-fluid">
						  				<div class="navbar-header">
											<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-8">
											            <span class="sr-only">Toggle navigation</span>
											            <span class="icon-bar"></span>
											            <span class="icon-bar"></span>
											            <span class="icon-bar"></span>
											</button>
											<span class="title navbar-brand"><h3>JR Buildings</h3></span>
						  				</div>
						  				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-8">
						    				<ul class="nav navbar-nav listitemheight">
						    					<li><a href=<%= buildings_path %>>Civic Addresses</a></li>
								    			<li><a href=<%= properties_path %>>Locals</a></li>
								    			<li><a href=<%= tenants_path %>>Tenants</a></li>
								    			<li><a href=<%= expenses_path %>>Expenses</a></li>
								    	
								    			<li><a href=<%= cheques_path %>>Cheques</a></li>
								    			<li><a href=<%= users_path %>>Personal</a></li>
								    			<li><a href=<%= helps_path %>>Help</a></li>
								    			<li><a href=<%= log_out_path %>>Log Out</a></li>
								  			</ul>
							  			</div>
							  			<div class="loggedin">
							  				Logged in as <%= current_user.email %>
							  			</div>
						    		</div>
						    	</nav>

								<%= yield %>
								
							</div>
			    	<% else %>
					    	 <div class="container">
					    	 	<% flash.each do |name, msg| %>
						    		<%= content_tag :div, msg, :id => "flash_#{name}" %>
						    	<% end %>

								<%= yield %>
					    		
					    	</div>
			    	<% end %>
			 </div>
		 

		</body>
	</div>
</html>