jrbuilding/config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end

end

Rails.application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "tenants/generate_lease" => "tenants#generate_lease"
  get "tenants/expense_addendum" => "tenants#expense_addendum"
  post "cheques/single_report" => "cheques#single_report"
  get "cheques/all_report" => "cheques#all_report"
  get "buildings/getgst" => "buildings#getgst"
  get "buildings/getqst" => "buildings#getqst"
  get "tenants/get_tenant_id" => "tenants#get_tenant_id"
  get "tenants/get_tenant_table" => "tenants#get_tenant_table"
  get "expenses/expensesforyear" => "expenses#expensesforyear"
  get "expenses/expenses_for_building" => "expenses#expenses_for_building"
  get "buildings/properties_for_building" => "buildings#properties_for_building"
  get "tenants/tenants_in_local" => "tenants#tenants_in_local"
  get "helps/download_master_lease"
  get "helps/download_master_expense" => "helps#download_master_expense"
  post "tenants/send_mail" => "tenants#send_mail"

  root :to => 'buildings#index', :constraints => AuthConstraint.new, as: :authenticated_root
  root :to => 'sessions#new'

  resources :users
  resources :buildings
  resources :properties
  resources :tenants
  resources :sessions 
  resources :expenses
  resources :masterleasepdfforms
  resources :expensepdfforms  
  resources :helps
  resources :cheques  
  match '*path', :to => 'errors#routing', via: [:get, :post]

end

jrbuilding/app/models/help.rb
class Help < ApplicationRecord
end

jrbuilding/app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  before_action :set_help, only: [:show, :edit, :update, :destroy]

  # GET /helps
  # GET /helps.json
  def index
    @helps = Help.all
  end

  # GET /helps/1
  # GET /helps/1.json
  def show
    redirect_to action: "index"
  end

  # GET /helps/new
  def new
    redirect_to action: "index"
  end

  # GET /helps/1/edit
  def edit
    redirect_to action: "index"
  end

  def download_master_lease
    send_file(
      "#{Rails.root}/lib/pdf_templates/master_lease.pdf",
      filename: "master_lease.pdf",
      type: "application/pdf"
    )
  end

  def download_master_expense
    send_file(
      "#{Rails.root}/lib/pdf_templates/expense_addendum_master.pdf",
      filename: "expense_addendum_master.pdf",
      type: "application/pdf"
    )
  end

  # POST /helps
  # POST /helps.json
  def create
    redirect_to action: "index"
    # @help = Help.new(help_params)

    # respond_to do |format|
    #   if @help.save
    #     format.html { redirect_to @help, notice: 'Help was successfully created.' }
    #     format.json { render :show, status: :created, location: @help }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @help.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /helps/1
  # PATCH/PUT /helps/1.json
  def update
    @help = Help.find_by_id(1)
    @allbuildings = Building.all
    @allbuildings.each do |b|
      b.gst = @help.gst
      b.qst = @help.qst
      b.save
    end
 
    respond_to do |format|
      if @help.update(help_params)
        format.html { redirect_to @help, notice: 'Help was successfully updated.' }
        format.json { render :show, status: :ok, location: @help }
        #redirect_to action: "index"
      else
        format.html { render :edit }
        format.json { render json: @help.errors, status: :unprocessable_entity }
        #redirect_to action: "index"
      end
    end
  end

  # DELETE /helps/1
  # DELETE /helps/1.json
  def destroy
    # @help.destroy
    # respond_to do |format|
    #   format.html { redirect_to helps_url, notice: 'Help was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    redirect_to action: "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_help
      # @help = Help.find(params[:id])
      rescue ActiveRecord::RecordNotFound  
          redirect_to root_url
       return
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def help_params
      params.require(:help).permit(:gst, :qst)
    end
end

jrbuilding/app/helpers/helps_helper.rb
module HelpsHelper
end

jrbuilding/app/views/helps/_form.html.erb
<%= form_for(@help) do |f| %>
  <% if @help.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@help.errors.count, "error") %> prohibited this help from being saved:</h2>

      <ul>
      <% @help.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

jrbuilding/app/views/helps/edit.html.erb
<h1>Editing help</h1>

<%= render 'form' %>

<%= link_to 'Show', @help %> |
<%= link_to 'Back', helps_path %>

jrbuilding/app/views/helps/index.html.erb
<head>
  <title>Help</title>
</head>
  
  <!-- Panel -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Help </h3>
      </div>


      
      <div class="panel-body"> 
      <div class="row">       
       <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading"><h5>Update Tax Rates</h5></div>
          <div class="panel-body">
            <% if current_user.admin? %>
              <% @help = Help.find_by_id(1) %>
              <%= bootstrap_form_for(@help) do |f| %>
                <% if @help.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@help.errors.count, "error") %> prohibited this tax rate from being saved:</h2>
                    <ul>
                    <% @help.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
                <%= f.hidden_field :id %>
                <div class="field">
                  <%= f.text_field :gst, label: "GST", :min => 0 %>
                </div>
                <div class="field">
                  <%= f.text_field :qst, label: "QST", :min => 0  %>
                </div>
                
                  <div class="actions">
                    <%= f.submit 'Update Taxes', :class=>"btn btn-success navbar-btn" %>
                  </div>
                <% end %>
              
            <% else %>
              <% @help = Help.find_by_id(1) %>
              <%= bootstrap_form_for(@help) do |f| %>
                <div class="field">
                  <%= f.text_field :gst, label: "GST", :readonly => true  %>
                </div>
                <div class="field">
                  <%= f.text_field :qst, label: "QST", :readonly => true  %>
                </div>
              <% end %>
            <% end %>
          </div>
          
        </div>
      </div>
      <div class="col-md-4">

        <div class="panel panel-default extend_box">
          <div class="panel-heading"><h5>Downloads</h5></div>
          <div class="panel-body">
            <p>Master Lease</p>
            <p>
              <%= link_to 'Download', "https://www.dropbox.com/s/4k53u162clnspr3/master_lease.pdf?dl=1" %>
            </p>
            <p>Master Expense Addendum</p>
            <p>
              <%= link_to 'Download', "https://www.dropbox.com/s/6mo76r431ucxsly/exp_add.pdf?dl=1" %>
            </p>
          </div>
          
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default extend_box">
          <div class="panel-heading"><h5>Developer / Site Help</h5></div>
          <div class="panel-body">
            <p>Mubarak Sadoon</p>
            <p>
              14168302476
            </p>
          </div>
          
        </div>
        </div>
        </div>
        <div class="row">
          <div class="col-md-12">
              <div class="panel panel-info">
                <div class="panel-heading">Remind Tenants of Upcoming Renewal (3 months before lease end) </div>
                <div class="panel-body scrollable">
                  <table class="table">
                    <thead> 
                      <tr>
                        <th>Tenant Name</th>
                        <th>Lease Expiry Date</th>
                        <th>Remind?</th>
                      </tr>
                    </thead>
                    
                    <tbody>
                      <% (Tenant.all).each do |k| %>
                        <% if (((k.leaseend) < (Time.now.to_date + 3.months)) && (k.leaseend > Time.now.to_date)) && (k.t_email != "" )%>
                          <tr>
                            <td><%= k.tenantname %></td>
                            <td><%= k.leaseend %></td>
                            <% if (k.t_email.blank?)%>
                            <% else %>
                             <td><%= button_to "Remind", { :controller => "tenants", :action => "send_mail", :tname => k.tenantname, :temail => k.t_email, :tleaseend => k.leaseend }, :class => 'btn btn-default' %></td>
                            <% end %>
                          </tr>
                        <% end %>
                      <% end %>
                    </tbody>
                  
                  </table>
                  
                </div>
              </div>
            </div> 
            <div class="col-lg-6">

            </div>
        </div>
      </div>
        
      
      
      <div class="panel-footer">
      </div>
    </div>

jrbuilding/app/views/helps/new.html.erb
<h1>New help</h1>

<%= render 'form' %>

<%= link_to 'Back', helps_path %>

jrbuilding/app/views/helps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_help_path(@help) %> |
<%= link_to 'Back', helps_path %>