jrbuilding/config/routes.rb
class AuthConstraint
  def matches?(request)
    request.session['user_id'].present?
  end

end

Rails.application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "tenants/generate_lease" => "tenants#generate_lease"
  get "tenants/expense_addendum" => "tenants#expense_addendum"
  post "cheques/single_report" => "cheques#single_report"
  get "cheques/all_report" => "cheques#all_report"
  get "buildings/getgst" => "buildings#getgst"
  get "buildings/getqst" => "buildings#getqst"
  get "tenants/get_tenant_id" => "tenants#get_tenant_id"
  get "tenants/get_tenant_table" => "tenants#get_tenant_table"
  get "expenses/expensesforyear" => "expenses#expensesforyear"
  get "expenses/expenses_for_building" => "expenses#expenses_for_building"
  get "buildings/properties_for_building" => "buildings#properties_for_building"
  get "tenants/tenants_in_local" => "tenants#tenants_in_local"
  get "helps/download_master_lease"
  get "helps/download_master_expense" => "helps#download_master_expense"
  post "tenants/send_mail" => "tenants#send_mail"

  root :to => 'buildings#index', :constraints => AuthConstraint.new, as: :authenticated_root
  root :to => 'sessions#new'

  resources :users
  resources :buildings
  resources :properties
  resources :tenants
  resources :sessions 
  resources :expenses
  resources :masterleasepdfforms
  resources :expensepdfforms  
  resources :helps
  resources :cheques  
  match '*path', :to => 'errors#routing', via: [:get, :post]

end

jrbuilding/app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.search(params[:search])
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    redirect_to action: "index"
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  def expenses_for_building
    s = Expense.for_building(params[:buildinginfo]).to_a.map(&:serializable_hash)
    @var = s.map { |x| x["year"]}
    @var2 = s.map { |x| x["yeartotal"] }
#     {"optionValue":10, "optionDisplay": "Remy"},
# {"optionValue":11, "optionDisplay": "Arif"},
# {"optionValue":12, "optionDisplay": "JC"}
    @var3 = Expense.createTag(@var, @var2)
    render text: @var3
  end

  def expensesforyear

    s = Expense.expenses_for_year(params[:year]).to_s('F')
    
    render text: s
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create

    @expense = Expense.new(expense_params)

    b_id = Building.search(@expense.buildinginfo)
    Building.find_by(id: b_id).expenses << @expense
    
    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    @updateTenants = []
    Tenant.all.each do |t|
      if @expense.year == t.expenseyear
        @updateTenants << t
      end
    end

    respond_to do |format|
      if @expense.update(expense_params)
        b_id = Building.search(@expense.buildinginfo)
        Building.find_by(id: b_id).expenses << @expense
        @updateTenants.each do |t|
          t.expenseyear = @expense.year
          t.save
        end
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
      rescue ActiveRecord::RecordNotFound  
          redirect_to root_url
       return
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:item1, :item2, :item3, :item4, :item5, :item6, :item7, :item8, :item9, :item10, :cost1, :cost2, :cost3, :cost4, :cost5, :cost6, :cost7, :cost8, :cost9, :cost10, :year, :yearend, :yeartotal, :buildinginfo)
    end
end

jrbuilding/app/helpers/expenses_helper.rb
module ExpensesHelper
end

jrbuilding/app/views/expenses/_expenses.html.erb
<div class="panel-body">        
            <!-- Each thumbnail -->
          
            <div class="row">

              <% if (@expenses.nil?) || (@expenses.count == 0) %>
                <h2>No Expenses</h2>
              <% else %>
              
              <% @expenses.each do |expense| %>
                 <div class="col-sm-6 col-md-4">
                  <div class="panel panel-default">
                    
                    <div class="panel-body">
                      <h5>Expense Year Start: <%= expense.year%></h5>
                      <h5>Expense Year End: <%= expense.yearend%></h5>
                      <% string = "CA: " + expense.buildinginfo %>
                      <h5><%= string.first(32) %></h5>
                      <p><h5>Year Total: <%='%.2f' % expense.yeartotal%></h5></p>
                      <p>
                        <a type="button" class="btn btn-primary navbar-btn" href=<%= edit_expense_path(expense) %>>Edit</a>  
                      </p>   
                    </div>
                  </div>
                 </div>
            
                <%end%>
              <%end%>
            </div>

        
        <div class="btn-group pull-right">
          <% b_all =  Building.all %>
            <% if b_all.count > 0 %>
              <%= link_to "Add Expense", new_expense_path, :class=>"btn btn-default navbar-btn" %>
            <% else %>
              <%= link_to "Add Expense", new_expense_path, :class=>"btn btn-default navbar-btn", :disabled => true %>
            <% end %>
          
      </div>
      </div>

jrbuilding/app/views/expenses/_form.html.erb
<!-- Panel -->
<div class="panel panel-default">
  <div class="panel-heading">
      <h3 class="panel-title">Expense Edit</h3>
  </div>
  
  <div class="panel-body">
    <%= bootstrap_form_for(@expense) do |f| %>
            <% if @expense.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>
                <ul>
                <% @expense.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
    <div class="row">
     <div class="col-md-4"> 
          <%= f.hidden_field :id %>
          <div class="field">
            <%= f.date_select :year, label: "Expense Year Start" %>
          </div>
          <div class="field">
            <%= f.date_select :yearend, label: "Expense Year End" %>
          </div>
          <div class="field" id="selection">
            <%= f.collection_select :buildinginfo, Building.all, :half_address, :half_address, {:label => "Civic Address Info"} %>
          </div>  
    
    </div>
  </div>

    <div class="row"> 
      <div class="col-lg-6"> 
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
      
          <tr>
            <th>1</th>
            <th>
              <div class="field">
                <%= f.text_field :item1, hide_label: true %>
              </div>
            </th>
            <th>
              <div class="field">
                <%= f.text_field :cost1, hide_label: true %>
              </div>
            </th>
          </tr>
          <tr>
            <th>2</th>
            <th>
              <div class="field">
                <%= f.text_field :item2, hide_label: true %>
              </div>
            </th>
            <th>
              <div class="field">
                <%= f.text_field :cost2, hide_label: true %>
              </div>
            </th>
          </tr>
          <tr>
            <th>3</th>
            <th>
              <div class="field">
                <%= f.text_field :item3, hide_label: true %>
              </div>
            </th>
            <th>
              <div class="field">
                <%= f.text_field :cost3, hide_label: true %>
              </div>
            </th>
          </tr>
          <tr>
            <th>4</th>
            <th>
              <div class="field">
                <%= f.text_field :item4, hide_label: true %>
              </div>
            </th>
            <th>
              <div class="field">
                <%= f.text_field :cost4, hide_label: true %>
              </div>
            </th>
          </tr>
          <tr>
            <th>5</th>
            <th>
              <div class="field">
                <%= f.text_field :item5, hide_label: true %>
              </div>
            </th>
            <th>
              <div class="field">
                <%= f.text_field :cost5, hide_label: true %>
              </div>
            </th>
          </tr>
          
          </tbody>
        </table>
        
          
            
         
        </div>
          <div class="col-lg-6"> 
          <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
      
          <tr>
            <th>6</th>
            <th>
              <div class="field">
                <%= f.text_field :item6, hide_label: true %>
              </div>
            </th>
            <th>
              <div class="field">
                <%= f.text_field :cost6, hide_label: true %>
              </div>
            </th>
          </tr>
          <tr>
            <th>7</th>
            <th>
              <div class="field">
                <%= f.text_field :item7, hide_label: true %>
              </div>
            </th>
            <th>
              <div class="field">
                <%= f.text_field :cost7, hide_label: true %>
              </div>
            </th>
          </tr>
          <tr>
            <th>8</th>
            <th>
              <div class="field">
                <%= f.text_field :item8, hide_label: true %>
              </div>
            </th>
            <th>
              <div class="field">
                <%= f.text_field :cost8, hide_label: true %>
              </div>
            </th>
          </tr>
          <tr>
            <th>9</th>
            <th>
              <div class="field">
                <%= f.text_field :item9, hide_label: true %>
              </div>
            </th>
            <th>
              <div class="field">
                <%= f.text_field :cost9, hide_label: true %>
              </div>
            </th>
          </tr>
          <tr>
            <th>10</th>
            <th>
              <div class="field">
                <%= f.text_field :item10, hide_label: true %>
              </div>
            </th>
            <th>
              <div class="field">
                <%= f.text_field :cost10, hide_label: true %>
              </div>
            </th>
          </tr>
          </tbody>
        </table>
        </div>
          
        
        
    
  </div>

  <div class="col-lg-6"> 
    
            <div class="field">
                    <%= f.text_field :yeartotal, value: number_with_precision(f.object.yeartotal, precision: 2), label: "Year Total", :readonly=>true %>
                  </div>
                    
            <div class="actions">
              <%= f.submit "Update Expense", :class => "btn btn-success" %>
            </div>
              <span id="delete">
                    <%= link_to "Delete", @expense, method: :delete, :class=>"btn btn-danger navbar-btn pull-right bot-right", data: { confirm: "Deleting this expense, also deletes all the cost items in it for the expense year"} %>
                    </span>
            </div>

            <% end %>

  </div>
  <div class="col-lg-6"> 
  </div>
  
  <div class="panel-footer">

        
  </div>
</div>

jrbuilding/app/views/expenses/edit.html.erb
<head>
	<title>Expense Edit</title>
</head>
  
   <%= render 'form' %>

jrbuilding/app/views/expenses/index.html.erb
<head>
  <title>Expenses List</title>
</head>
  
  <!-- Panel -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Expenses List </h3>
      </div>

      <div class="panel-body">        
        <div class="row">
          
               

          <div class="col-md-6 col-drop">
               <div class="input-group">
                      
                      <%= form_tag expenses_path, :id => "expenses_filter_building", :method => 'get' do %>
                        
                        <%= collection_select @building, :search, Building.all, :half_address, :half_address, {:prompt => "Civic Address"}, {:class => "form-control", :id => "index_expense_building_select"} %>
        
                      <% end %>                      
                </div>
          </div> 
          <div class="col-md-6 col-drop">
               <div class="input-group">
                      
                      <%= form_tag expenses_path, :id => "expenses_filter_year", :method => 'get' do %>
                        
                        <%= collection_select @expense, :search, Expense.years_only, :year_only, :year_only, {:prompt => "Expense Year"}, {:class => "form-control", :id => "index_expense_year_select"}  %>
                        
                      <% end %>                   
                </div>

          </div>
               
             
        </div>
      </div>
        
      
      <div id="filteredexpenses">
          <%= render 'expenses' %>
      </div>
      <div class="panel-footer">
      </div>
    </div>

jrbuilding/app/views/expenses/index.js.erb
$("#filteredexpenses").html("<%= escape_javascript(render("expenses")) %>")

jrbuilding/app/views/expenses/new.html.erb
<head>
	<title>Expense Edit</title>
</head>
  
   <%= render 'form' %>

jrbuilding/app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>